apps/psicologo/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import permission_required
from views import *

urlpatterns = [
    url(r'^$', index_psicologo, name = 'index'),
    url(r'^listar/grupos/(?P<pk>\d+)$', permission_required('administrador.soypsicologo', login_url = '/accounts/login/')(psicologoGrupoList),
        name = 'grupo_listar'),
    url(r'^listar/(?P<grupo_id>\d+)/estudiantes$', permission_required('administrador.soypsicologo', login_url = '/accounts/login/')(psicologoEstudianteList),
        name = 'estudiante_listar'),
    url(r'^listar/(?P<est_id>\d+)/tests$', permission_required('administrador.soypsicologo', login_url = '/accounts/login/')(psicologoEstudianteTestList),
        name = 'estudiante_test_listar'),

    url(r'^asignar/(?P<est_id>\d+)/tests$', permission_required('administrador.soypsicologo', login_url = '/accounts/login/')(psicologoAsignarTest),
        name = 'asignar_test'),
]

ptti/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib import admin
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.views import password_change, password_change_done
from django.shortcuts import render
from apps.administrador.views import *

def index(request):
    return render(request, 'index.html')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^administrador/', include('apps.administrador.urls', namespace = "administrador")),
    url(r'^estudiante/', include('apps.estudiante.urls', namespace = "estudiante")),
    url(r'^psicologo/', include('apps.psicologo.urls', namespace = "psicologo")),
    url(r'^$', index, name= "index"),
    url(r'^accounts/login/$', login, {'template_name': 'login.html'}, name = "login"),
    url(r'^logout/$', logout_then_login, name = "logout"),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'registration/password_reset_form.html',
        'email_template_name':'registration/password_reset_email.html'},
        name = 'password_reset'),
    url(r'^reset/password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name = 'password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name = 'password_reset_confirm'),
    url(r'^reset/done', password_reset_complete,
        {'template_name': 'registration/password_reset_complete.html'},
        name = 'password_reset_complete'),
    url(r'^editar/perfil/(?P<pk>\d+)$', login_required(login_url = '/accounts/login/')(UsuarioEditar.as_view()),
            name='editar_perfil'),
    url(r'^editar/password/$', login_required(login_url = '/accounts/login/')(UsuarioEditarPassword),
            name='editar_password'),

]

apps/administrador/models.py
# coding=utf-8

from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
TIPO_DOCUMENTO = (
    ('CC', 'Cedula de Ciudadania'),
    ('TI', 'Tarjeta de Identidad'),
    ('RI', 'Registro Civil')
)

# CLASE ADMINISTRADOR -> TIENE LLAVE FORANEA DE USUARIO
class Administrador(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    cargoInstitucional = models.TextField(max_length = 140, default = '', blank = True)
    tipoDocumento = models.CharField(max_length = 2, choices = TIPO_DOCUMENTO)
    docIdentidad = models.CharField(max_length = 10, primary_key = True)#, unique = True)
    fechaDeNacimiento = models.DateField(null = True, blank = True)
    direccion = models.CharField(max_length = 120)
    telefono = models.CharField(max_length = 10, blank = True)

    def _str_(self):
        return 'Admin. ' + self.user.first_name

    class Meta:
        permissions = (
            ('administrar', 'Puede administrar'),
        )

# CLASE INSTITUCION
class Institucion(models.Model):
    nit = models.CharField(max_length = 20, primary_key = True)
    nombre = models.CharField(max_length = 70, unique = True)
    telefono = models.CharField(max_length = 10)
    email = models.EmailField(max_length = 50)
    paginaWeb = models.URLField(max_length = 200)
    direccion = models.CharField(max_length = 100)

    def __str__(self):
        return self.nombre

# CLASE PSICOLOGO
class Psicologo(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    tipoDocumento = models.CharField(max_length = 2, choices = TIPO_DOCUMENTO)
    docIdentidad = models.CharField(max_length = 10, primary_key = True)#, unique = True)
    fechaDeNacimiento = models.DateField(null = True, blank = True)
    direccion = models.CharField(max_length = 100)
    telefono = models.CharField(max_length = 10, blank = True)
    titulo = models.CharField(max_length = 100) # Titulo Universitario
    institucion = models.ForeignKey(Institucion, on_delete = models.CASCADE, null = True)

    def __str__(self):
        return self.user.first_name +' '+ self.user.last_name

    class Meta:
        permissions = (
            ('soypsicologo', 'Puedo ejercer'),
            ("ver_evaluacion_psicologo", "Puede ver las evaluaciones"),
            ("ver_diagnostico_psicologo", "Puede ver los diagnosticos"),
            ("realizar_diagnostico", "Puede realizar un diagnostico")
        )

# CLASE GRUPO
#class Grupo(models.Model):
class Grupo(models.Model):
    psicologo = models.ForeignKey(Psicologo, on_delete=models.CASCADE) # Un psicologo puede tener varios grupos
    institucion = models.ForeignKey(Institucion, on_delete = models.CASCADE)
    JORNADA = (
            ('JM', 'Jornada Mañana'),
            ('JT', 'Jornada Tarde'),
            ('JE', 'Jornada Especial')
            )
    jornada = models.CharField(max_length = 2, choices = JORNADA)
    nombre_grado = models.CharField(max_length = 30, null = True)

    def __str__(self):
        return self.nombre_grado+' '+self.institucion.nombre

# CLASE ESTUDIANTE
class Estudiante(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    tipoDocumento = models.CharField(max_length = 2, choices = TIPO_DOCUMENTO)
    docIdentidad = models.CharField(max_length = 10, primary_key = True)#, unique = True)
    fechaDeNacimiento = models.DateField(null = True, blank = True)
    direccion = models.CharField(max_length = 100)
    telefono = models.CharField(max_length = 10, blank = True)
    grupo = models.ForeignKey(Grupo, on_delete = models.CASCADE, null = True) # Un grupo tiene varios alumnos

    class Meta:
        permissions = (
            ("ver_test_estudiante", "Puede ver los test"),
            ("ver_diagnostico", "Puede ver los diagnosticos")
        )

    def __str__(self):
        return self.user.first_name+" "+self.user.last_name

# CLASE TEST (Tipos de test)
class Test(models.Model):
    descripcion = models.CharField(max_length = 40, unique = True)

    def __str__(self):
        return self.descripcion

# CLASE TEST ASIGNADO:
class TestAsignado(models.Model):
    estudiante = models.ForeignKey(Estudiante, on_delete = models.CASCADE)
    test = models.ForeignKey(Test, on_delete = models.CASCADE)
    #respuestas = models.ForeignKey(Respuestas, on_delete = models.CASCADE)

# CLASE PREGUNTAS
class Pregunta(models.Model):
    pregunta = models.TextField()
    numero = models.CharField(max_length = 10, null = True)
    test = models.ForeignKey(Test, on_delete = models.CASCADE)

    def __str__(self):
        return self.pregunta+' '+str(self.test.id)

apps/psicologo/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/psicologo/forms.py
# coding=utf-8

from django import forms
from ..administrador.models import *

# FORMULARIO PARA LA ASIGNACIÓN DE TEST
class TestAsignadoForm(forms.ModelForm):
    class Meta:
        model = TestAsignado
        fields = [
            'estudiante',
            'test',
        ]
        labels = {
            'estudiante' : 'Asignar al estudiante',
            'test' : 'Tipo de Test',
        }

apps/psicologo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import permission_required
from ..administrador.models import *
from forms import *
# Create your views here.


@permission_required('administrador.soypsicologo', login_url='/accounts/login/')
def index_psicologo(request):
    return render(request, 'psicologo/index.html')
    #return HttpResponse("Soy la pagina principal de Un psicologo")

# VISTAS PARA EL LISTADO DE ELEMENTOS

# Listar los grupos que tiene asignado un psicologo:
@permission_required('administrador.soypsicologo', login_url='/accounts/login/')
def psicologoGrupoList(request, pk):
    # Buscar el objeto psicologo, con el id que tiene el usuario activo actual
    psicologo = Psicologo.objects.get(user_id = pk)
    # Filtrar los resultador por el psicologo
    grupos_list = Grupo.objects.order_by('nombre_grado').filter(psicologo = psicologo.docIdentidad)
    context = {'grupos_list':grupos_list, 'psicologo':psicologo.docIdentidad}
    return render(request, 'psicologo/grupo_list.html', context)

# Listar los alumnos que tienen los grupos asociados al psicologo
@permission_required('administrador.soypsicologo', login_url='/accounts/login/')
def psicologoEstudianteList(request, grupo_id):
    estudiante_list = Estudiante.objects.order_by('docIdentidad').filter(grupo = grupo_id)
    context = {'estudiante_list':estudiante_list, 'grupo':grupo_id}
    return render(request, 'psicologo/estudiante_list.html', context)

# Listar los test que tiene asignado un estudiante
@permission_required('administrador.soypsicologo', login_url='/accounts/login/')
def psicologoEstudianteTestList(request, est_id):
    estudiante = Estudiante.objects.get(docIdentidad = est_id)
    testAsignado_list = TestAsignado.objects.filter(estudiante = est_id)
    context = {'testAsignado_list':testAsignado_list, 'estudiante':estudiante}
    return render(request, 'psicologo/estudiante_test_list.html', context)

# Asignar test a un estudiante
@permission_required('administrador.soypsicologo', login_url='/accounts/login/')
def psicologoAsignarTest(request, est_id):
    estudiante = Estudiante.objects.get(docIdentidad = est_id)
    if request.method == 'POST':
        form = TestAsignadoForm(request.POST)
        print "DATOS INGRESADOS---------->"
        print form
        if form.is_valid():
            form.save()
            return psicologoEstudianteTestList(request, est_id)
    else:
        form = TestAsignadoForm()
    return render(request, 'psicologo/asignar_test_form.html', {'form':form, 'estudiante':estudiante})

templates/psicologo/asignar_test_form.html
{% extends 'administrador/index.html'%}

{% block content %}
<h2>ASIGNAR UN TEST</h2>

<form method="post">
  {% csrf_token %}

<div class="form-horizontal">
  <fieldset>
    <legend>Ingresar datos</legend>

    <div class="form-group">
      <label for="{{form.estudiante.name}}" class="col-lg-5 control-label">{{form.estudiante.label}}</label>
      <div class="col-lg-1">
        <select id="id_estudiante" name="estudiante" required="">
          <option value="{{ estudiante.pk }}" selected="selected">{{ estudiante.user.first_name }}{{ estudiante.user.last_name }}</option>
        </select>
      </div>
    </div>

    <div class="form-group">
      <label for="{{form.test.name}}" class="col-lg-5 control-label">{{form.test.label}}</label>
      <div class="col-lg-1">
      {{form.test}}
      </div>
    </div>

  </fieldset>
</div>

  <div class="form-group">
    <div class="col-lg-8 col-lg-offset-2">
      <button type="reset" class="btn btn-default">Resetar</button>
      <button type="submit" class="btn btn-primary">Asignar</button>
    </div>
  </div>
</form>
{% endblock %}

templates/psicologo/estudiante_list.html
{% extends 'psicologo/index.html'%}

{% block content %}
  <h2>LISTA DE ESTUDIANTES</h2>

  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <td>#</td>
        <td>Documento de Identidad</td>
        <td>Nombres</td>
        <td>Apellidos</td>
        <td>Fecha de Nacimiento</td>
        <td>Email</td>
        <td>Direccion</td>
        <td>Telefono</td>
        <td colspan="1">Acciones</td>
      </tr>
    </thead>

    <tbody>
      {% if estudiante_list %}
        <h3>Grupo {{ grupo }}</h3>
      {% for estudiante in estudiante_list %}
      <tr>
        <td>{{ estudiante.user.id }}</td>
        <td>{{ estudiante.docIdentidad }}</td>
        <td>{{ estudiante.user.first_name }}</td>
        <td>{{ estudiante.user.last_name }}</td>
        <td>{{ estudiante.fechaDeNacimiento }}</td>
        <td>{{ estudiante.user.email }}</td>
        <td>{{ estudiante.direccion }}</td>
        <td>{{ estudiante.telefono }}</td>
        <td>
          <a class="btn btn-primary" href="{% url 'psicologo:estudiante_test_listar' estudiante.pk %}">Ver Tests Asignados</a>
        </td>
      </tr>
      {% endfor %}

      {% else %}
      <h1>NO HAY REGISTROS DE ESTUDIANTES</h1>

      {% endif %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/psicologo/estudiante_test_list.html
{% extends 'psicologo/index.html'%}

{% block content %}
  <p style="text-align: left;">
    <a class="btn btn-primary" href="{% url 'psicologo:asignar_test' estudiante.pk %}">Nuevo Test</a>
  </p>

  <h2>LISTA DE TEST ASIGNADOS</h2>

  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <td>#</td>
        <td>Test</td>
        <td colspan="1">Acciones</td>
      </tr>
    </thead>

    <tbody>
      {% if testAsignado_list %}
        <h3>Estudiante {{ estudiante.user.first_name }} {{ estudiante.user.last_name }}</h3>
      {% for testAsignado in testAsignado_list %}
      <tr>
        <td>{{ testAgignado.id }}</td>
        <td>{{ testAsignado.test }}</td>
        <td>
          <a class="btn btn-primary" href="#">Quitar</a>
        </td>
      </tr>
      {% endfor %}

      {% else %}
      <h1>NO HAY REGISTROS DE TESTS</h1>

      {% endif %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/psicologo/grupo_list.html
{% extends 'psicologo/index.html'%}

{% block content %}
  <h2>LISTA DE GRUPOS</h2>

  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <td>#</td>
        <td>Institución</td>
        <td>Jornada</td>
        <td>Grado</td>
        <td colspan="2">Acciones</td>
      </tr>
    </thead>

    <tbody>
      {% if grupos_list %}
      {% for grupo in grupos_list %}
      <tr>
        <td>{{ grupo.id }}</td>
        <td>{{ grupo.institucion }}</td>
        <td>{{ grupo.jornada }}</td>
        <td>{{ grupo.nombre_grado }}</td>
        <td>
          <a class="btn btn-info" href="{% url 'psicologo:estudiante_listar' grupo.pk %}">Ver Alumnos</a>
        </td>
      </tr>
      {% endfor %}

      {% else %}
      <h3>NO HAY REGISTROS DE GRUPOS</h3>

      {% endif %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/psicologo/index.html
{% extends 'base/base.html'%}

{% block title%}Psicologo{% endblock %}

{% block home %}
  <a class="navbar-brand" href="{% url 'psicologo:index' %}">Inicio</a>
{% endblock %}

{% block navbar %}
  <li><a href="{% url 'psicologo:grupo_listar' user.pk %}">Mis grupos</a></li>
{% endblock %}

{% block content %}
<h2> APP DEL PSICOLOGO</h2>

<h4>  Datos del psicologo </h4>
  Usuario : {{ user.username }}   <br>
  Correo  : {{ user.email}}       <br>
  Nombre  : {{ user.first_name }} <br>
  Apellido: {{ user.last_name }}  <br>
<p><a class="btn btn-primary btn-lg" href="{% url 'editar_perfil' user.pk%}">Editar</a></p>
<p><a class="btn btn-primary btn-lg" href="{% url 'editar_password'%}">Editar Contraseña</a></p>

<a href="javascript:window.history.go(-1);">Pagina de Inicio</a>
{% endblock %}