apps/administrador/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.views import password_change, password_change_done
from views import *


urlpatterns = [
    url(r'^$', index_administrador, name = 'index'),
    url(r'^listar/psicologos$', permission_required('administrador.administrar', login_url = '/accounts/login/')(PsicologoList.as_view()),
        name = 'psicologo_listar'),
    url(r'^listar/estudiantes$', permission_required('administrador.administrar', login_url = '/accounts/login/')(EstudianteList.as_view()),
        name = 'estudiante_listar'),
    url(r'^listar/instituciones$', permission_required('administrador.administrar', login_url = '/accounts/login/')(InstitucionList.as_view()),
        name = 'instituciones_listar'),
    url(r'^listar/grupo$', permission_required('administrador.administrar', login_url = '/accounts/login/')(GrupoList.as_view()),
        name = 'grupo_listar'),
    url(r'^listar/test$', permission_required('administrador.administrar', login_url = '/accounts/login/')(TestList.as_view()),
        name = 'test_listar'),
    url(r'^listar/preguntas/(?P<test_id>\d+)$', permission_required('administrador.administrar', login_url = '/accounts/login/')(PreguntaList),
        name = 'pregunta_listar'),

    url(r'^crear/psicologos$', permission_required('administrador.administrar', login_url = '/accounts/login/')(PsicologoCrear.as_view()),
        name = 'psicologo_crear'),
    url(r'^crear/estudiantes$', permission_required('administrador.administrar', login_url = '/accounts/login/')(EstudianteCrear.as_view()),
        name = 'estudiante_crear'),
    url(r'^crear/instituciones$', permission_required('administrador.administrar', login_url = '/accounts/login/')(InstitucionCrear.as_view()),
        name = 'instituciones_crear'),
    url(r'^crear/grupo$', permission_required('administrador.administrar', login_url = '/accounts/login/')(GrupoCrear.as_view()),
        name = 'grupo_crear'),
    url(r'^crear/test$', permission_required('administrador.administrar', login_url = '/accounts/login/')(TestCrear.as_view()),
        name = 'test_crear'),
    url(r'^crear/preguntas/(?P<test_id>\d+)$', permission_required('administrador.administrar', login_url = '/accounts/login/')(PreguntaCrear),
        name = 'pregunta_crear'),

    url(r'^editar/psicologos/(?P<pk>\d+)$', permission_required('administrador.administrar', login_url = '/accounts/login/')(PsicologoEditar.as_view()),
        name = 'psicologo_editar'),
    url(r'^editar/estudiantes/(?P<pk>\d+)$', permission_required('administrador.administrar', login_url = '/accounts/login/')(EstudianteEditar.as_view()),
        name = 'estudiante_editar'),
    url(r'^editar/instituciones/(?P<pk>\d+)$', permission_required('administrador.administrar', login_url = '/accounts/login/')(InstitucionEditar.as_view()),
        name = 'instituciones_editar'),
    url(r'^editar/grupo/(?P<pk>\d+)$', permission_required('administrador.administrar', login_url = '/accounts/login/')(GrupoEditar.as_view()),
        name = 'grupo_editar'),
    url(r'^editar/test/(?P<pk>\d+)$', permission_required('administrador.administrar', login_url = '/accounts/login/')(TestEditar.as_view()),
        name = 'test_editar'),
    url(r'^editar/pregunta/(?P<pre_id>\d+)/(?P<test_id>\d+)$', permission_required('administrador.administrar', login_url = '/accounts/login/')(PreguntaEditar),
        name = 'pregunta_editar'),

    url(r'^eliminar/psicologos/(?P<pk>\d+)$', permission_required('administrador.administrar', login_url = '/accounts/login/')(PsicologoEliminar),
        name = 'psicologo_eliminar'),
    url(r'^eliminar/estudiantes/(?P<pk>\d+)$', permission_required('administrador.administrar', login_url = '/accounts/login/')(EstudianteEliminar),
        name = 'estudiante_eliminar'),
    url(r'^eliminar/instituciones/(?P<pk>\d+)$', permission_required('administrador.administrar', login_url = '/accounts/login/')(InstitucionEliminar),
        name = 'instituciones_eliminar'),
    url(r'^eliminar/grupo/(?P<pk>\d+)$', permission_required('administrador.administrar', login_url = '/accounts/login/')(GrupoEliminar),
        name = 'grupo_eliminar'),
    url(r'^eliminar/test/(?P<pk>\d+)$', permission_required('administrador.administrar', login_url = '/accounts/login/')(TestEliminar),
        name = 'test_eliminar'),
    url(r'^eliminar/pregunta/(?P<pre_id>\d+)/(?P<test_id>\d+)$', permission_required('administrador.administrar', login_url = '/accounts/login/')(PreguntaEliminar),
        name = 'pregunta_eliminar'),
]

apps/estudiante/urls.py
from django.conf.urls import url, include
from views import index_estudiante

urlpatterns = [
    url(r'^$', index_estudiante, name = 'index'),
]

apps/psicologo/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import permission_required
from views import *

urlpatterns = [
    url(r'^$', index_psicologo, name = 'index'),
    url(r'^listar/grupos/(?P<pk>\d+)$', permission_required('administrador.soypsicologo', login_url = '/accounts/login/')(psicologoGrupoList),
        name = 'grupo_listar'),
    url(r'^listar/(?P<grupo_id>\d+)/estudiantes$', permission_required('administrador.soypsicologo', login_url = '/accounts/login/')(psicologoEstudianteList),
        name = 'estudiante_listar'),
    url(r'^listar/(?P<est_id>\d+)/tests$', permission_required('administrador.soypsicologo', login_url = '/accounts/login/')(psicologoEstudianteTestList),
        name = 'estudiante_test_listar'),

    url(r'^asignar/(?P<est_id>\d+)/tests$', permission_required('administrador.soypsicologo', login_url = '/accounts/login/')(psicologoAsignarTest),
        name = 'asignar_test'),
]

ptti/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib import admin
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.views import password_change, password_change_done
from django.shortcuts import render
from apps.administrador.views import *

def index(request):
    return render(request, 'index.html')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^administrador/', include('apps.administrador.urls', namespace = "administrador")),
    url(r'^estudiante/', include('apps.estudiante.urls', namespace = "estudiante")),
    url(r'^psicologo/', include('apps.psicologo.urls', namespace = "psicologo")),
    url(r'^$', index, name= "index"),
    url(r'^accounts/login/$', login, {'template_name': 'login.html'}, name = "login"),
    url(r'^logout/$', logout_then_login, name = "logout"),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'registration/password_reset_form.html',
        'email_template_name':'registration/password_reset_email.html'},
        name = 'password_reset'),
    url(r'^reset/password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name = 'password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name = 'password_reset_confirm'),
    url(r'^reset/done', password_reset_complete,
        {'template_name': 'registration/password_reset_complete.html'},
        name = 'password_reset_complete'),
    url(r'^editar/perfil/(?P<pk>\d+)$', login_required(login_url = '/accounts/login/')(UsuarioEditar.as_view()),
            name='editar_perfil'),
    url(r'^editar/password/$', login_required(login_url = '/accounts/login/')(UsuarioEditarPassword),
            name='editar_password'),

]

apps/administrador/models.py
# coding=utf-8

from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
TIPO_DOCUMENTO = (
    ('CC', 'Cedula de Ciudadania'),
    ('TI', 'Tarjeta de Identidad'),
    ('RI', 'Registro Civil')
)

# CLASE ADMINISTRADOR -> TIENE LLAVE FORANEA DE USUARIO
class Administrador(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    cargoInstitucional = models.TextField(max_length = 140, default = '', blank = True)
    tipoDocumento = models.CharField(max_length = 2, choices = TIPO_DOCUMENTO)
    docIdentidad = models.CharField(max_length = 10, primary_key = True)#, unique = True)
    fechaDeNacimiento = models.DateField(null = True, blank = True)
    direccion = models.CharField(max_length = 120)
    telefono = models.CharField(max_length = 10, blank = True)

    def _str_(self):
        return 'Admin. ' + self.user.first_name

    class Meta:
        permissions = (
            ('administrar', 'Puede administrar'),
        )

# CLASE INSTITUCION
class Institucion(models.Model):
    nit = models.CharField(max_length = 20, primary_key = True)
    nombre = models.CharField(max_length = 70, unique = True)
    telefono = models.CharField(max_length = 10)
    email = models.EmailField(max_length = 50)
    paginaWeb = models.URLField(max_length = 200)
    direccion = models.CharField(max_length = 100)

    def __str__(self):
        return self.nombre

# CLASE PSICOLOGO
class Psicologo(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    tipoDocumento = models.CharField(max_length = 2, choices = TIPO_DOCUMENTO)
    docIdentidad = models.CharField(max_length = 10, primary_key = True)#, unique = True)
    fechaDeNacimiento = models.DateField(null = True, blank = True)
    direccion = models.CharField(max_length = 100)
    telefono = models.CharField(max_length = 10, blank = True)
    titulo = models.CharField(max_length = 100) # Titulo Universitario
    institucion = models.ForeignKey(Institucion, on_delete = models.CASCADE, null = True)

    def __str__(self):
        return self.user.first_name +' '+ self.user.last_name

    class Meta:
        permissions = (
            ('soypsicologo', 'Puedo ejercer'),
            ("ver_evaluacion_psicologo", "Puede ver las evaluaciones"),
            ("ver_diagnostico_psicologo", "Puede ver los diagnosticos"),
            ("realizar_diagnostico", "Puede realizar un diagnostico")
        )

# CLASE GRUPO
#class Grupo(models.Model):
class Grupo(models.Model):
    psicologo = models.ForeignKey(Psicologo, on_delete=models.CASCADE) # Un psicologo puede tener varios grupos
    institucion = models.ForeignKey(Institucion, on_delete = models.CASCADE)
    JORNADA = (
            ('JM', 'Jornada Mañana'),
            ('JT', 'Jornada Tarde'),
            ('JE', 'Jornada Especial')
            )
    jornada = models.CharField(max_length = 2, choices = JORNADA)
    nombre_grado = models.CharField(max_length = 30, null = True)

    def __str__(self):
        return self.nombre_grado+' '+self.institucion.nombre

# CLASE ESTUDIANTE
class Estudiante(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    tipoDocumento = models.CharField(max_length = 2, choices = TIPO_DOCUMENTO)
    docIdentidad = models.CharField(max_length = 10, primary_key = True)#, unique = True)
    fechaDeNacimiento = models.DateField(null = True, blank = True)
    direccion = models.CharField(max_length = 100)
    telefono = models.CharField(max_length = 10, blank = True)
    grupo = models.ForeignKey(Grupo, on_delete = models.CASCADE, null = True) # Un grupo tiene varios alumnos

    class Meta:
        permissions = (
            ("ver_test_estudiante", "Puede ver los test"),
            ("ver_diagnostico", "Puede ver los diagnosticos")
        )

    def __str__(self):
        return self.user.first_name+" "+self.user.last_name

# CLASE TEST (Tipos de test)
class Test(models.Model):
    descripcion = models.CharField(max_length = 40, unique = True)

    def __str__(self):
        return self.descripcion

# CLASE TEST ASIGNADO:
class TestAsignado(models.Model):
    estudiante = models.ForeignKey(Estudiante, on_delete = models.CASCADE)
    test = models.ForeignKey(Test, on_delete = models.CASCADE)
    #respuestas = models.ForeignKey(Respuestas, on_delete = models.CASCADE)

# CLASE PREGUNTAS
class Pregunta(models.Model):
    pregunta = models.TextField()
    numero = models.CharField(max_length = 10, null = True)
    test = models.ForeignKey(Test, on_delete = models.CASCADE)

    def __str__(self):
        return self.pregunta+' '+str(self.test.id)

apps/estudiante/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/psicologo/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/psicologo/forms.py
# coding=utf-8

from django import forms
from ..administrador.models import *

# FORMULARIO PARA LA ASIGNACIÓN DE TEST
class TestAsignadoForm(forms.ModelForm):
    class Meta:
        model = TestAsignado
        fields = [
            'estudiante',
            'test',
        ]
        labels = {
            'estudiante' : 'Asignar al estudiante',
            'test' : 'Tipo de Test',
        }

apps/estudiante/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import permission_required

# Create your views here.
@permission_required('administrador.ver_test_estudiante', login_url='/accounts/login/')
def index_estudiante(request):
    return render(request, 'estudiante/index.html')
    #return HttpResponse("Soy la pagina principal de Estudiante")

apps/psicologo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import permission_required
from ..administrador.models import *
from forms import *
# Create your views here.


@permission_required('administrador.soypsicologo', login_url='/accounts/login/')
def index_psicologo(request):
    return render(request, 'psicologo/index.html')
    #return HttpResponse("Soy la pagina principal de Un psicologo")

# VISTAS PARA EL LISTADO DE ELEMENTOS

# Listar los grupos que tiene asignado un psicologo:
@permission_required('administrador.soypsicologo', login_url='/accounts/login/')
def psicologoGrupoList(request, pk):
    # Buscar el objeto psicologo, con el id que tiene el usuario activo actual
    psicologo = Psicologo.objects.get(user_id = pk)
    # Filtrar los resultador por el psicologo
    grupos_list = Grupo.objects.order_by('nombre_grado').filter(psicologo = psicologo.docIdentidad)
    context = {'grupos_list':grupos_list, 'psicologo':psicologo.docIdentidad}
    return render(request, 'psicologo/grupo_list.html', context)

# Listar los alumnos que tienen los grupos asociados al psicologo
@permission_required('administrador.soypsicologo', login_url='/accounts/login/')
def psicologoEstudianteList(request, grupo_id):
    estudiante_list = Estudiante.objects.order_by('docIdentidad').filter(grupo = grupo_id)
    context = {'estudiante_list':estudiante_list, 'grupo':grupo_id}
    return render(request, 'psicologo/estudiante_list.html', context)

# Listar los test que tiene asignado un estudiante
@permission_required('administrador.soypsicologo', login_url='/accounts/login/')
def psicologoEstudianteTestList(request, est_id):
    estudiante = Estudiante.objects.get(docIdentidad = est_id)
    testAsignado_list = TestAsignado.objects.filter(estudiante = est_id)
    context = {'testAsignado_list':testAsignado_list, 'estudiante':estudiante}
    return render(request, 'psicologo/estudiante_test_list.html', context)

# Asignar test a un estudiante
@permission_required('administrador.soypsicologo', login_url='/accounts/login/')
def psicologoAsignarTest(request, est_id):
    estudiante = Estudiante.objects.get(docIdentidad = est_id)
    if request.method == 'POST':
        form = TestAsignadoForm(request.POST)
        print "DATOS INGRESADOS---------->"
        print form
        if form.is_valid():
            form.save()
            return psicologoEstudianteTestList(request, est_id)
    else:
        form = TestAsignadoForm()
    return render(request, 'psicologo/asignar_test_form.html', {'form':form, 'estudiante':estudiante})

templates/administrador/estudiante_eliminar.html
{% extends 'administrador/index.html'%}


{% block content %}
<h1>PRECAUCIÓN: ELIMINADO ESTUDIANTE</h1>
<form method="post">
  {% csrf_token %}
  <h3>¿Desea Eliminar el registro de {{ estudiante.user.first_name }}{{ estudiante.user.last_name }}?</h3>

  <button class="btn btn-danger" type="submit">SÍ, eliminar</button>
  <a class="btn btn-default" href="{% url 'administrador:estudiante_listar' %}">Cancelar</a>

</form>

<br>
Nota: Se guardará un registro indicando quien fue el administrador que elimino al estudiante

{% endblock %}

templates/administrador/estudiante_list.html
{% extends 'administrador/index.html'%}

{% block content %}
  <p style="text-align: left;">
    <a class="btn btn-primary" href="{% url 'administrador:estudiante_crear' %}">Nuevo Estudiante</a>
  </p>

  <h2>LISTA DE ESTUDIANTES</h2>

  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <td>#</td>
        <td>Grupo</td>
        <td>Institucion</td>
        <td>Email</td>
        <td>Nombres</td>
        <td>Apellidos</td>
        <td>Documento de Identidad</td>
        <td>Fecha de Nacimiento</td>
        <td>Direccion</td>
        <td>Telefono</td>
        <td colspan="2">Acciones</td>
      </tr>
    </thead>

    <tbody>
      {% if object_list %}
      {% for estudiante in object_list %}
      <tr>
        <td>{{ estudiante.user.id }}</td>
        <td>{{ estudiante.grupo.nombre_grado }}</td>
        <td>{{ estudiante.grupo.institucion }}</td>
        <td>{{ estudiante.user.email }}</td>
        <td>{{ estudiante.user.first_name }}</td>
        <td>{{ estudiante.user.last_name }}</td>
        <td>{{ estudiante.docIdentidad }}</td>
        <td>{{ estudiante.fechaDeNacimiento }}</td>
        <td>{{ estudiante.direccion }}</td>
        <td>{{ estudiante.telefono }}</td>
        <td>
          <a class="btn btn-primary" href="{% url 'administrador:estudiante_editar' estudiante.pk %}">Editar</a>
        </td>
        <td>
          <a class="btn btn-danger" href="{% url 'administrador:estudiante_eliminar' estudiante.pk %}">Eliminar</a>
        </td>
      </tr>
      {% endfor %}

      {% else %}
      <h1>NO HAY REGISTROS DE ESTUDIANTES</h1>

      {% endif %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/administrador/grupo_eliminar.html
{% extends 'administrador/index.html'%}


{% block content %}
<h1>PRECAUCIÓN: ELIMINADO GRUPO</h1>
<form method="post">
  {% csrf_token %}
  <h3>¿Desea Eliminar el registro del grupo {{ grupo.nombre_grado }} de la I.E {{ grupo.institucion }}?</h3>

  <button class="btn btn-danger" type="submit">SÍ, eliminar</button>
  <a class="btn btn-default" href="{% url 'administrador:grupo_listar' %}">Cancelar</a>

</form>

<br>
Nota: Se guardará un registro indicando quien fue el administrador que elimino el grupo

{% endblock %}

templates/administrador/index.html
{% extends 'base/base.html'%}

{% block title%}App Administrador{% endblock %}

{% block home %}
  <a class="navbar-brand" href="{% url 'administrador:index' %}">Inicio</a>
{% endblock %}

{% block navbar %}
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Psicologo <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><a href="{% url 'administrador:psicologo_crear' %}">Registrar</a></li>
      <li><a href="{% url 'administrador:psicologo_listar' %}">Listar</a></li>
    </ul>
  </li>

  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Estudiante <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><a href="{% url 'administrador:estudiante_crear' %}">Registrar</a></li>
      <li><a href="{% url 'administrador:estudiante_listar' %}">Listar</a></li>
    </ul>
  </li>

  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Instituciones <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><a href="{% url 'administrador:instituciones_crear' %}">Registrar</a></li>
      <li><a href="{% url 'administrador:instituciones_listar' %}">Listar</a></li>
    </ul>
  </li>

  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Grupos <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><a href="{% url 'administrador:grupo_crear' %}">Registrar</a></li>
      <li><a href="{% url 'administrador:grupo_listar' %}">Listar</a></li>
    </ul>
  </li>

  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Evaluaciones<span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><a href="{% url 'administrador:test_crear' %}">Registrar</a></li>
      <li><a href="{% url 'administrador:test_listar' %}">Listar</a></li>
    </ul>
  </li>

{% endblock %}


{% block content %}
  <h2>APP DEL ADMINISTRADOR</h2>
  <h4>  Datos del administrador </h4>
    Usuario : {{ user.username }}   <br>
    Correo  : {{ user.email}}       <br>
    Nombre  : {{ user.first_name }} <br>
    Apellido: {{ user.last_name }}  <br>
  <h4> Tiene las siguientes facultades </h5>
    - Gestionar psicologos    <br>
    - Gestionar estudiantes   <br>
    - Gestionar instituciones <br> <br>
  <p><a class="btn btn-primary btn-lg" href="{% url 'editar_perfil' user.pk%}">Editar</a></p>
  <p><a class="btn btn-primary btn-lg" href="{% url 'editar_password'%}">Editar Contraseña</a></p>

  <a href="javascript:window.history.go(-1);">Pagina de Inicio</a>
{% endblock %}

templates/administrador/pregunta_eliminar.html
{% extends 'administrador/index.html'%}


{% block content %}
<h1>PRECAUCIÓN: ELIMINADO PREGUNTA</h1>
<form method="post">
  {% csrf_token %}
  <h3>¿Desea Eliminar el registro Pregunta "{{ pregunta.pregunta }}" del test {{ test }}?</h3>

  <button class="btn btn-danger" type="submit">SÍ, eliminar</button>
  <a class="btn btn-default" href="{% url 'administrador:pregunta_listar' test %}">Cancelar</a>

</form>

<br>
Nota: Se guardará un registro indicando quien fue el administrador que elimino la pregunta

{% endblock %}

templates/administrador/pregunta_form.html
{% extends 'administrador/index.html'%}

{% block content %}
<h2>CREAR UNA PREGUNTA</h2>

<form method="post">
  {% csrf_token %}

<div class="form-horizontal">
  <fieldset>
    <legend>Ingresar datos</legend>

    <div class="form-group">
      <label for="{{form.pregunta.name}}" class="col-lg-5 control-label">{{form.pregunta.label}}</label>
      <div class="col-lg-2">
      {{form.pregunta}}
      </div>
    </div>

    <div class="form-group">
      <label for="{{form.numero.name}}" class="col-lg-5 control-label">{{form.numero.label}}</label>
      <div class="col-lg-2">
      {{form.numero}}
      </div>
    </div>

    <div class="form-group">
      <label for="{{form.test.name}}" class="col-lg-5 control-label">{{form.test.label}}</label>
      <div class="col-lg-1">
        <select id="id_test" name="test" required="">
          <option value="{{ test }}" selected="selected">TEST {{ test }}</option>
        </select>
      </div>
    </div>

  </fieldset>
</div>

  <div class="form-group">
    <div class="col-lg-8 col-lg-offset-2">
      <button type="reset" class="btn btn-default">Resetar</button>
      <button type="submit" class="btn btn-primary">Crear</button>
    </div>
  </div>
</form>
{% endblock %}

templates/administrador/pregunta_list.html
{% extends 'administrador/index.html'%}

{% block content %}
  <p style="text-align: left;">
    <a class="btn btn-primary" href="{% url 'administrador:pregunta_crear' test %}">Nueva Pregunta</a>
  </p>

  <h2>LISTA DE PREGUNTAS</h2>
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <td>#</td>
        <td>Numero</td>
        <td>Pregunta</td>
        <td colspan="3">Acciones</td>
      </tr>
    </thead>

    <tbody>
      {% if pregunta_list %}

      {% for pregunta in pregunta_list %}
      <tr>
        <td>{{ pregunta.id }}</td>
        <td>{{ pregunta.numero }}</td>
        <td>{{ pregunta.pregunta }}</td>
        <td>
          <a class="btn btn-primary" href="{% url 'administrador:pregunta_editar' pregunta.id test %}">Editar</a>
        </td>
        <td>
          <a class="btn btn-danger" href="{% url 'administrador:pregunta_eliminar' pregunta.id test %}">Eliminar</a>
        </td>
      </tr>
      {% endfor %}

      {% else %}
      <h3>NO HAY REGISTROS DE PREGUNTAS EN ESTE TEST</h3>

      {% endif %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/administrador/psicologo_eliminar.html
{% extends 'administrador/index.html'%}

{% block content %}

<h1>PRECAUCIÓN: ELIMINADO PSICOLOGO</h1>
<form method="post">
  {% csrf_token %}
  <h3>¿Desea Eliminar el registro de {{ psicologo.user.first_name }}{{ psicologo.user.last_name }}?</h3>

  <button class="btn btn-danger" type="submit">SÍ, eliminar</button>
  <a class="btn btn-default" href="{% url 'administrador:psicologo_listar' %}">Cancelar</a>

</form>

<br>
Nota: Se guardará un registro indicando quien fue el administrador que elimino al psicologo

{% endblock %}

templates/administrador/test_list.html
{% extends 'administrador/index.html'%}

{% block content %}
  <p style="text-align: left;">
    <a class="btn btn-primary" href="{% url 'administrador:test_crear' %}">Nuevo Test</a>
  </p>

  <h2>LISTA DE TEST</h2>

  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <td>#</td>
        <td>Descripcion</td>
        <td colspan="3">Acciones</td>
      </tr>
    </thead>

    <tbody>
      {% if object_list %}
      {% for test in object_list %}
      <tr>
        <td>{{ test.id }}</td>
        <td>{{ test.descripcion }}</td>
        <td>
          <a class="btn btn-primary" href="{% url 'administrador:test_editar' test.pk %}">Editar</a>
        </td>
        <td>
          <a class="btn btn-info" href="{% url 'administrador:pregunta_listar' test.pk %}">Preguntas</a>
        </td>
        <td>
          <a class="btn btn-danger" href="{% url 'administrador:test_eliminar' test.pk %}">Eliminar</a>
        </td>
      </tr>
      {% endfor %}

      {% else %}
      <h1>NO HAY REGISTROS DE ESTUDIANTES</h1>

      {% endif %}
    </tbody>
  </table>
</div>
{% endblock %}