ptti/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib import admin
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.views import password_change, password_change_done
from django.shortcuts import render
from apps.administrador.views import *

def index(request):
    return render(request, 'index.html')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^administrador/', include('apps.administrador.urls', namespace = "administrador")),
    url(r'^estudiante/', include('apps.estudiante.urls', namespace = "estudiante")),
    url(r'^psicologo/', include('apps.psicologo.urls', namespace = "psicologo")),
    url(r'^$', index, name= "index"),
    url(r'^accounts/login/$', login, {'template_name': 'login.html'}, name = "login"),
    url(r'^logout/$', logout_then_login, name = "logout"),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'registration/password_reset_form.html',
        'email_template_name':'registration/password_reset_email.html'},
        name = 'password_reset'),
    url(r'^reset/password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name = 'password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name = 'password_reset_confirm'),
    url(r'^reset/done', password_reset_complete,
        {'template_name': 'registration/password_reset_complete.html'},
        name = 'password_reset_complete'),
    url(r'^editar/perfil/(?P<pk>\d+)$', login_required(login_url = '/accounts/login/')(UsuarioEditar.as_view()),
            name='editar_perfil'),
    url(r'^editar/password/$', login_required(login_url = '/accounts/login/')(UsuarioEditarPassword),
            name='editar_password'),

]

templates/editar.html
{% extends 'base/base.html'%}

{% block content %}
<h2>Editar Mi perfil</h2>

<form method="post">
	{% csrf_token %}
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.username.name}}">{{form.username.label}}</label>
				{{form.username}}
			</div>
		</div>

    <div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.email.name}}">{{form.email.label}}</label>
				{{form.email}}
			</div>
		</div>

		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.first_name.name}}">{{form.first_name.label}}</label>
				{{form.first_name}}
			</div>
		</div>

    <div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.last_name.name}}">{{form.last_name.label}}</label>
				{{form.last_name}}
			</div>
		</div>

    <div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.email.name}}">{{form.email.label}}</label>
				{{form.email}}
			</div>
		</div>

	</div>
	<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary" type="submit">Guardar</button>
			</div>
</div>
</form>
{% endblock %}

templates/editar_password.html
{% extends 'base/base.html'%}

{% block content %}
<h2>Editar Mi contraseña</h2>

<form method="post">
  {% csrf_token %}
  <div class="form-horizontal">
    <fieldset>
      <legend>Repleta los campos</legend>

      <div class="form-group">
        <label for="{{form.old_password.name}}" class="col-lg-5 control-label">{{form.old_password.label}}</label>
        <div class="col-lg-2">
          {{form.old_password}}
        </div>
      </div>

      <div class="form-group">
        <label for="{{form.new_password1.name}}" class="col-lg-5 control-label">{{form.new_password1.label}}</label>
        <div class="col-lg-2">
          {{form.new_password1}}
        </div>
      </div>

      <div class="form-group">
        <label for="{{form.new_password2.name}}" class="col-lg-5 control-label">{{form.new_password2.label}}</label>
        <div class="col-lg-2">
        {{form.new_password2}}
        </div>
      </div>
    </fieldset>
  </div>
  <div class="form-group">
    <div class="col-lg-8 col-lg-offset-2">
      <button type="reset" class="btn btn-default">Resetar</button>
      <button type="submit" class="btn btn-primary">Cambiar</button>
    </div>
  </div>
</form>

{% endblock %}

templates/index.html
{% extends 'base/base.html' %}

{% block title %}
PTTI
{% endblock %}

{% block logout %}
	<ul class="nav navbar-nav navbar-right">
		<li><a href="{% url 'administrador:index' %}">Ingreso Admin</a></li>
	</ul>
{% endblock %}

{% block content %}

<div>
	<a href="{% url 'estudiante:index' %}" class="btn btn-primary btn-lg" role="button">Ingreso Estudiantes</a>
	<a href="{% url 'psicologo:index' %}" class="btn btn-default btn-lg" role="button">Ingreso Psicologos</a>
</div>

{% endblock %}

templates/login.html
{% extends 'base/base.html' %}

{% block title %}
PTTI
{% endblock %}

{% block navbar%}
{% endblock %}

{% block logout %}
{% endblock %}

{% block content %}
<h2>INGRESAR A LA PLATAFORMA</h2>

<form method="post">
	{% csrf_token %}
	 <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="username">Nombre de usuario:</label>
        		<input class="form-control" type="text" name="username">
    	   </div>
        </div>
    </div>
    <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="username">Contraseña:</label>
        		<input class="form-control" type="password" name="password">
    	   </div>
        </div>
    </div>
    <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<input class="btn btn-primary" type="submit" value="INGRESAR">
						<a href="{% url 'index' %}" class="btn btn-default" role="button">VOLVER AL INDEX</a>
     	   </div>
				 <a href="{% url 'password_reset' %}">Olvidé mi contraseña</a>
        </div>
    </div>

</form>

{% endblock %}